#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Lote 3: cauda do Reversed Fate (frases curtas repetidas + restantes), didático."""
import json, glob, re, unicodedata
def norm(s):
    s = unicodedata.normalize('NFC', s or '')
    s = s.replace('’',"'").replace('‘',"'").replace('“','"').replace('”','"')
    return re.sub(r'\s+',' ', s).strip()

C = [
 # --- recorrentes (glossário: stat boost=buff dele, espeed=Extreme Speed, b4=antes, comes in/out=entra) ---
 ["Encore depois stat boost", "Encore depois do buff dele"],
 ["Encore depois stat boost?", "Encore depois do buff dele?"],
 ["Encore depois stat boost? testar", "Encore depois do buff dele? · testar"],
 ["Encore depois stat boost? Testing", "Encore depois do buff dele? (em teste)"],
 ["Encore again depois stat boost", "Encore de novo depois do buff dele"],
 ["Encore once depois stat boost", "Um Encore depois do buff dele"],
 ["Encore depois stat boost para save $", "Encore depois do buff dele · pra economizar"],
 ["Encore depois stat boost any work", "Encore depois do buff dele (testar se funciona)"],
 ["No u turn · Encore depois stat boost", "Sem U-turn · Encore depois do buff dele"],
 ["Wary of hp", "Cuidado com o HP"],
 ["wary of hp", "Cuidado com o HP"],
 ["Be wary of Health", "Cuidado com o HP"],
 ["Wary of hp cura se precisa", "Cuidado com o HP · cure se precisar"],
 ["Max Potion b4 pressione", "Max Potion antes de pressionar"],
 ["Max Potion b4 pushing", "Max Potion antes de pressionar"],
 ["precisa data", "Falta testar"],
 ["precisa more data", "Falta testar mais"],
 ["testar precisa data", "Falta testar"],
 ["precisa testing", "Falta testar"],
 ["Testing", "Em teste"],
 ["no data yet", "Sem dados ainda"],
 # --- HOENN ---
 ["precisa data on troque para gyara", "Falta testar: troca pro Gyarados"],
 ["Wary of hp · use X Defesa ?", "Cuidado com o HP · use X Defesa?"],
 ["Chandelure[+2 Ataque Especial, +2 Velocidade] (solve is roll)", "Chandelure[+2 Ataque Especial, +2 Velocidade] (solve é roll/incerta)"],
 ["troque para gyara precisa data/Shadow Ball nocauteia Garchomp · fire fang flinch Stealth Rock again",
  "Troca pro Gyarados (falta testar) · Shadow Ball nocauteia o Garchomp · Fire Fang causa flinch · Stealth Rock de novo"],
 ["Wait till Electivire comes in", "Espere o Electivire entrar"],
 ["Shadow Ball tenta · Scrafty Crunch is a roll precisa better solve", "Tente Shadow Ball · o Crunch do Scrafty é roll · precisa de solve melhor"],
 ["Gallade kills", "Gallade nocauteia"],
 ["No star Encore · Scrafty Encore . Roll on Earthquake Jirachi ? X Velocidade primeiro se não usa nocauteia Jirachi",
  "Jirachi sem Encore · Scrafty dá Encore · Earthquake no Jirachi é roll? · X Velocidade primeiro se não nocautear o Jirachi"],
 ["Runs during strength Veja abaixo", "Se ele fugir durante o buff, veja abaixo"],
 ["Psycho Cut kills Garchomp?", "Psycho Cut nocauteia o Garchomp?"],
 ["crítico Max Potion. Wary of espeed", "Se tomar crítico, Max Potion · cuidado com o Extreme Speed"],
 ["crítico Encore sacrifica/ try no medicine ? Probably won't work try Chandelure fire nocauteia",
  "Se tomar crítico, Encore e sacrifica · tente sem cura? · provavelmente não funciona · tente o fogo do Chandelure pra nocautear"],
 ["precisa para solve on Jirachi / testar se HP kills Raichu", "Precisa de solve pro Jirachi · testar se o HP nocauteia o Raichu"],
 ["pode use jirachi se still tem berry", "Dá pra usar o Jirachi se ainda tiver berry"],
 ["Dragon pluse Lucario does 62% para Dragonite wary of health se no Stealth Rock .",
  "Dragon Pulse · o Lucario causa 62% no Dragonite · cuidado com o HP se não tiver Stealth Rock"],
 ["Save money: Chandelure · Pikachu[Encore, +4 Ataque Especial, +2 Velocidade]",
  "Pra economizar: Chandelure · Pikachu[Encore, +4 Ataque Especial, +2 Velocidade]"],
 ["No star Encore · Scrafty Encore . testar se Fire Blast is a roll", "Jirachi sem Encore · Scrafty dá Encore · testar se o Fire Blast é roll"],
 ["No Jirachi Encore · Scrafty Encore . Roll on Metagross. precisa better solve Chandelure fire nocauteia Metagross se it comes in last?",
  "Jirachi sem Encore · Scrafty dá Encore · é roll no Metagross · precisa de solve melhor · o fogo do Chandelure nocauteia o Metagross se ele entrar por último?"],
 ["Runs para Walrein/dewgong continuar / toss does 33% para star Gallade se egg is last",
  "Se trocar pro Walrein/Dewgong, continue · o Seismic Toss causa 33% no Jirachi · Gallade se o Exeggutor for o último"],
 ["Chandelure consume faint", "Chandelure se sacrifica (desmaia)"],
 ["testar Chandelure · Jirachi · chande · Mismagius comes in setup w Scrafty",
  "Testar Chandelure · Jirachi · Chandelure · se o Mismagius entrar, faça setup com o Scrafty"],
 ["Remove poison primeiro · flame thrower once b4 pressione? troque para Walrein/Dewgong continuar",
  "Tire o veneno primeiro · um Flamethrower antes de pressionar? · se trocar pro Walrein/Dewgong, continue"],
 ["Runs Nidoqueen Veja abaixo. Dance once · drain punch · x Ataque. · dance Drain punch togekis. precisa crítico solve on Scrafty e Walrein · beat up Metagross?",
  "Se trocar pro Nidoqueen, veja abaixo · um Dragon Dance · Drain Punch · X Ataque · Dragon Dance e Drain Punch no Togekiss · precisa de solve pra crítico no Scrafty e Walrein · Beat Up no Metagross?"],
 ["Shadow Ball Nidoqueen lives HP", "Shadow Ball no Nidoqueen · ele sobrevive com HP"],
 ["Wary of hp. cura se precisa. No shadow sneak by Gallade at 23.8%", "Cuidado com o HP · cure se precisar · o Gallade não leva Shadow Sneak a 23,8%"],
 ["crítico Max Potion star. Be wary of e Velocidade", "Se o Jirachi tomar crítico, Max Potion · cuidado com o empate de Velocidade"],
 ["Max Potion b4 pressione? testar Encore lead storm", "Max Potion antes de pressionar? · testar Encore no Leaf Storm"],
 ["Encore depois stat boost/ Psycho Cut ampy", "Encore depois do buff dele · Psycho Cut no Ampharos"],
 ["Dragon Rush Gallade/ precisa data on Stone Edge crítico Dragonite", "Dragon Rush no Gallade · falta testar Stone Edge crítico no Dragonite"],
 ["precisa crítico solve wary of health", "Precisa de solve pra caso de crítico · cuidado com o HP"],
 ["cura b4 pressione", "Cure antes de pressionar"],
 ["precisa data on espeed on Pikachu . crítico Encore sacrifica · Chandelure · Pikachu strengthen?",
  "Falta testar o Extreme Speed no Pikachu · se tomar crítico, Encore e sacrifica · Chandelure · bufar o Pikachu?"],
 ["Jirachi Thunderbolt once", "Jirachi · um Thunderbolt"],
 ["Encore Leaf Storm · Chandelure Max Potion b4 pressione", "Encore no Leaf Storm · Chandelure · Max Potion antes de pressionar"],
 ["Shadow Ball amp · Max Potion b4 pressione", "Shadow Ball no Ampharos · Max Potion antes de pressionar"],
 ["Stays nocauteia", "Se ele ficar, nocauteia"],
 ["precisa data on no Choice (preso num golpe)", "Falta testar sem Choice (preso num golpe)"],
 ["Wary of Rocky Helmet on Milo", "Cuidado com o Rocky Helmet do Milotic"],
 ["Stays se para", "Ele fica (não troca)"],
 ["Wary of Milotic Rocky Helmet · pode Energy Root b4 pressione for insurance",
  "Cuidado com o Rocky Helmet do Milotic · dá pra usar Energy Root antes de pressionar por garantia"],
 # --- JOHTO ---
 ["crítico on Jirachi e stays Max Potion para force troca", "Se o Jirachi tomar crítico e ele ficar, use Max Potion pra forçar a troca"],
 ["Gallade[+2 Ataque, +2 Velocidade] Max Potion b4 pressione", "Gallade[+2 Ataque, +2 Velocidade] · Max Potion antes de pressionar"],
 ["Chandelure shadow once", "Chandelure · um Shadow Ball"],
 ["Encore depois stat boost? · psycho Garchomp", "Encore depois do buff dele? · Psycho Cut no Garchomp"],
 ["Leaf Blade quag · testar se Leaf Blade kills Gengar", "Leaf Blade no Quagsire · testar se o Leaf Blade nocauteia o Gengar"],
 ["Wary of hp Bullet Punch Dragonite[3x Dragon Dance (+3 Ataque +3 Velocidade)] 9%",
  "Cuidado com o HP · Bullet Punch · Dragonite[3x Dragon Dance (+3 Ataque, +3 Velocidade)] (9%)"],
 ["🐭gets burned/crítico/dies", "Se o Pikachu for queimado / tomar crítico / morrer"],
 ["Wary of espeed precisa Fire Blast miss solve e crítico", "Cuidado com o Extreme Speed · precisa de solve pra Fire Blast errar e pra crítico"],
 ["testar Dragonite[Encore, +2 Ataque, +2 Velocidade] · Encore depois stat boost · Scizor Bullet Punch at 56% · troque para Lapras Veja abaixo",
  "Testar Dragonite[Encore, +2 Ataque, +2 Velocidade] · Encore depois do buff dele · Bullet Punch do Scizor a 56% · troca pro Lapras, veja abaixo"],
 ["Rocky Helmet solve não usa work. Only leaves when star is dead e Gallade comes in",
  "A solve do Rocky Helmet não funciona · ele só sai quando o Jirachi morre e o Gallade entra"],
 ["Hone claws once · runs para Lapras Dragonite[1x Dragon Dance (+1 Ataque +1 Velocidade)] pressione",
  "Um Hone Claws · se trocar pro Lapras · Dragonite[1x Dragon Dance (+1 Ataque, +1 Velocidade)] · pressione"],
 ["crítico star · Scrafty Encore . cura b4 pressione. testar Chandelure[+2 Ataque Especial, +2 Velocidade]",
  "Se o Jirachi tomar crítico · Scrafty dá Encore · cure antes de pressionar · testar Chandelure[+2 Ataque Especial, +2 Velocidade]"],
 ["Wary of hp Dragonite espeed testar how HP baixo pode be", "Cuidado com o HP · Dragonite · Extreme Speed · testar quão baixo o HP pode ficar"],
 ["Wary of hp · Dragonite espeed", "Cuidado com o HP · Dragonite · Extreme Speed"],
 # --- KANTO ---
 ["Psycho Exeggutor. Encore depois stat boost", "Psycho Cut no Exeggutor · Encore depois do buff dele"],
 ["roll. crítico · Pikachu Encore · Shadow Ball Machamp", "É roll · se crítico · Pikachu dá Encore · Shadow Ball no Machamp"],
 ["testar. stays be wary of hp. cura se precisa", "Testar · se ele ficar, cuidado com o HP · cure se precisar"],
 ["Star crítico with Encore · troca Chandelure · troca Pikachu strengthen?? testar",
  "Se o Jirachi tomar crítico com Encore · troca pro Chandelure · troca pro Pikachu pra bufar? · testar"],
 ["Pikachu no boost", "Pikachu sem buff"],
 ["Wary of star health", "Cuidado com o HP do Jirachi"],
 ["Max put b4 pressione · Dragon Rush Garchomp", "Max Potion antes de pressionar · Dragon Rush no Garchomp"],
 ["Aura Sphere · Life Orb try. Stealth Rock · Encore · Chandelure fire nocauteia · gator comes out · Scrafty X Defesa+ [+5 Ataque, +2 Velocidade]. Beat up Dragonite",
  "Aura Sphere · tente com Life Orb · Stealth Rock · Encore · o fogo do Chandelure nocauteia · se o Feraligatr (gator) entrar · Scrafty X Defesa [+5 Ataque, +2 Velocidade] · Beat Up no Dragonite"],
 ["troque para Dragonite precisa data", "Troca pro Dragonite (falta testar)"],
 ["X Velocidade primeiro · cura poison · Max Potion b4 pressione · e Velocidade at 34%",
  "X Velocidade primeiro · cure o veneno · Max Potion antes de pressionar · empate de Velocidade a 34%"],
 ["Wary of hp. Add se precisa", "Cuidado com o HP · adicione se precisar"],
 ["Espeed kills Dragonite[3x Dragon Dance (+3 Ataque +3 Velocidade)] 0%", "Extreme Speed nocauteia o Dragonite[3x Dragon Dance (+3 Ataque, +3 Velocidade)] (0%)"],
 ["Max put b4 pressione · Shadow Ball Garchomp · end water gator Gallade nocauteia",
  "Max Potion antes de pressionar · Shadow Ball no Garchomp · no fim, contra o Feraligatr (water/gator) o Gallade nocauteia"],
 ["testar who para Encore with", "Testar com quem dar Encore"],
 ["Wary of hp. testar when e Velocidade hits", "Cuidado com o HP · testar quando o empate de Velocidade pega"],
 ["Bullet Punch does 49% Dragonite · cura se precisa", "Bullet Punch causa 49% no Dragonite · cure se precisar"],
 ["Runs para skar · star Thunderbolt · Gallade[Encore, +2 Ataque, +2 Velocidade] · Max Potion b4 pressione",
  "Se trocar pro Skarmory · Jirachi Thunderbolt · Gallade[Encore, +2 Ataque, +2 Velocidade] · Max Potion antes de pressionar"],
 ["Not contra Alakazam when u turn · Chandelure nocauteia/sacrifica. precisa data on who comes next",
  "Não contra o Alakazam ao dar U-turn · o Chandelure nocauteia/sacrifica · falta testar quem entra depois"],
 ["troque para skar continuar · wary of hp/Jirachi Thunderbolt · u turn · Gallade[Encore, +2 Ataque, +2 Velocidade]",
  "Troca pro Skarmory e continue · cuidado com o HP · Jirachi Thunderbolt · U-turn · Gallade[Encore, +2 Ataque, +2 Velocidade]"],
 ["No Encore · Pikachu Encore runs para Umbreon continuar strength", "Sem Encore · Pikachu dá Encore · se trocar pro Umbreon, continue bufando"],
 ["Wary of Air Balloon", "Cuidado com o Air Balloon"],
 ["crítico star · Scrafty Encore · Scizor does 49% para Dragonite be wary of hp",
  "Se o Jirachi tomar crítico · Scrafty dá Encore · o Scizor causa 49% no Dragonite · cuidado com o HP"],
 ["Bullet Punch does 47.7. crítico 66.2", "Bullet Punch causa 47,7% · crítico 66,2%"],
 # --- SINNOH ---
 ["Encore depois stat boost? testar", "Encore depois do buff dele? · testar"],
 ["Jirachi crítico · Scrafty Encore · unsure solve", "Se o Jirachi tomar crítico · Scrafty dá Encore · solve incerta"],
 ["Jirachi pode't Encore · Chandelure sacrifica e cura Jirachi · Jirachi Encore",
  "O Jirachi não consegue dar Encore · Chandelure se sacrifica e cura o Jirachi · Jirachi dá Encore"],
 ["Dance2+x Ataque testing", "Dragon Dance [+2] + X Ataque (em teste)"],
 ["Jirachi crítico · troca Scrafty Encore · still testing", "Se o Jirachi tomar crítico · troca pro Scrafty e dá Encore · ainda em teste"],
 ["Runs para Gliscor Scrafty Encore · Gallade[+2 Ataque, +2 Velocidade] testing",
  "Se trocar pro Gliscor · Scrafty dá Encore · Gallade[+2 Ataque, +2 Velocidade] (em teste)"],
 ["Encore depois stat boost? Testing / troque para Vespiquen continuar strength",
  "Encore depois do buff dele? (em teste) · se trocar pro Vespiquen, continue bufando"],
 ["Encore depois stat boost? Testing / troque para Vespiquen continuar strengthen",
  "Encore depois do buff dele? (em teste) · se trocar pro Vespiquen, continue bufando"],
 ["Star not full hp Stealth Rock sacrifica · Scrafty[Encore, 3x Dragon Dance (+3 Ataque +3 Velocidade)] se Draco · Earthquake go Gallade Max Potion b4 pressione",
  "Se o Jirachi não estiver com HP cheio · Stealth Rock e sacrifica · Scrafty[Encore, 3x Dragon Dance (+3 Ataque, +3 Velocidade)] · se vier Draco Meteor · Earthquake · vá de Gallade · Max Potion antes de pressionar"],
 ["Stays se para. Next time try Chandelure[+2 Velocidade]", "Se ele ficar · da próxima vez tente Chandelure[+2 Velocidade]"],
 ["Encore depois stat boost · foretress comes out Veja abaixo", "Encore depois do buff dele · se o Forretress entrar, veja abaixo"],
 ["Encore depois stat boost · Forretress nocauteia is a roll", "Encore depois do buff dele · nocautear o Forretress é roll"],
 ["se froze · unsure. precisa solve. Shadow Ball Gengar", "Se congelar · incerto · precisa de solve · Shadow Ball no Gengar"],
 ["Foretress comes out Veja abaixo. Sacred Sword Tangrowth · testar Psycho Cut", "Se o Forretress entrar, veja abaixo · Sacred Sword no Tangrowth · testar Psycho Cut"],
 ["Encore depois stat boost para save $", "Encore depois do buff dele · pra economizar"],
 ["Houndoom sash wary of hp", "Houndoom com Sash · cuidado com o HP"],
 ["se HJK solve não usa work try · Chandelure consume faint · Jirachi sacrifica · Scrafty Encore · Chandelure[+2 Ataque Especial, +2 Velocidade] se Steelix comes in b4 setup go Gallade[Encore, +2 Ataque, +2 Velocidade]",
  "Se a solve do High Jump Kick não funcionar, tente · Chandelure se sacrifica · Jirachi se sacrifica · Scrafty dá Encore · Chandelure[+2 Ataque Especial, +2 Velocidade] · se o Steelix entrar antes do setup, vá de Gallade[Encore, +2 Ataque, +2 Velocidade]"],
 ["Encore when it runs out/ x Velocidade primeiro ? testar", "Encore quando ele acabar · X Velocidade primeiro? · testar"],
 ["Wary of hp · cura infront of empleon · testar se precisa", "Cuidado com o HP · cure na frente do Empoleon · testar se precisa"],
 ["precisa data on team 7", "Falta testar contra o time 7"],
 ["Wary of espeed Lucario", "Cuidado com o Extreme Speed do Lucario"],
 ["Runs para Empoleon Chandelure not full hp · go Dragonite[+1 Ataque, +2 Velocidade]",
  "Se trocar pro Empoleon · Chandelure sem HP cheio · vá de Dragonite[+1 Ataque, +2 Velocidade]"],
 ["X Velocidade primeiro · runs para Dragonite pressione · Gallade comes out Veja abaixo",
  "X Velocidade primeiro · se trocar pro Dragonite, pressione · se o Gallade entrar, veja abaixo"],
 ["cura se hit two times in a row. any potion that gets u para max hp · wary of Rough Skin e espeed at 30%",
  "Cure se tomar dois golpes seguidos · qualquer poção que te leve ao HP máximo · cuidado com o Rough Skin e o Extreme Speed a 30%"],
 ["Psycho Cut Togekiss/Garchomp star lives crítico Veja abaixo", "Psycho Cut no Togekiss/Garchomp · o Jirachi sobrevive ao crítico, veja abaixo"],
 ["Wary of Ice Shard. testar how HP baixo pode be", "Cuidado com o Ice Shard · testar quão baixo o HP pode ficar"],
 # --- UNOVA ---
 ["Won't work se -spe Defesa · add x spe Defesa is so", "Não funciona se a Defesa Especial cair · use X Defesa Especial"],
 ["stays Thunderbolt e use any medicine para full cura. pode take up para 7 turns. precisa new solve",
  "Se ele ficar · Thunderbolt e use qualquer cura pra encher o HP · pode levar até 7 turnos · precisa de solve nova"],
 ["use Max Potion b4 Encore ?? testing", "Use Max Potion antes do Encore? (em teste)"],
 ["no data on no Choice (preso num golpe) testing", "Sem dados pra sem Choice (preso num golpe) · em teste"],
 ["stays Thunderbolt again", "Se ele ficar · Thunderbolt de novo"],
 ["precisa data for chande wo choice item", "Falta testar o Chandelure sem item Choice"],
 ["precisa data on npc running para Dragonite", "Falta testar o NPC trocando pro Dragonite"],
 ["se para use cura ou se hp is low Full Restore still testing start process over",
  "Se ele ficar, use cura · se o HP estiver baixo, ele usa Full Restore · ainda em teste, recomece o processo"],
 ["Flamethrower Gengar se Bisharp ko. testar se Energy Ball kills rotom", "Flamethrower no Gengar se o Bisharp for nocauteado · testar se o Energy Ball nocauteia o Rotom"],
 ["jirachi burn u turn para Scrafty Encore Chandelure[+2 Ataque Especial, +2 Velocidade] SBall bannette · check it Fire Blast is a roll on Scrafty",
  "Jirachi queimado · U-turn pro Scrafty · Encore · Chandelure[+2 Ataque Especial, +2 Velocidade] · Shadow Ball no Banette · confira: o Fire Blast no Scrafty é roll"],
 ["Runs para Chandelure Veja abaixo/runs para Milotic Encore e it runs para chande Choice (preso num golpe) · Chandelure[+2 Ataque Especial, +2 Velocidade] unsure",
  "Se trocar pro Chandelure, veja abaixo · se trocar pro Milotic, Encore · e se trocar pro Chandelure (preso no golpe pela Choice) · Chandelure[+2 Ataque Especial, +2 Velocidade] (incerto)"],
 ["nocauteia se it stays", "Nocauteia se ele ficar"],
 ["Liepard comes out", "Se o Liepard entrar"],
 ["se it gets haxs e dies Scrafty[+4 Ataque, +2 Velocidade] x attack", "Se ele tomar hax e morrer · Scrafty[+4 Ataque, +2 Velocidade] · X Ataque"],
 ["testar wo X Defesa", "Testar sem X Defesa"],
 ["Encore again depois stat boost/ x Velocidade primeiro ? testar", "Encore de novo depois do buff dele · X Velocidade primeiro? · testar"],
 ["Encore depois stat boost troque para meta nocauteia · contra Emolga x Velocidade pressione",
  "Encore depois do buff dele · troca pro Metagross e nocauteia · contra o Emolga, X Velocidade e pressione"],
 ["se - defense won't work", "Se a Defesa cair, não funciona"],
 ["A roll para nocauteia?", "É roll pra nocautear?"],
 ["Encore sacrifica jirachi se below 16%/ Encore depois stat boost", "Encore e sacrifica o Jirachi se abaixo de 16% · Encore depois do buff dele"],
 ["Fica troca Scrafty testing. testar opening with Stealth Rock", "Fica · troca pro Scrafty (em teste) · testar abrir com Stealth Rock"],
 ["Max Potion depois stat boost ? testar where Max Potion is precisa", "Max Potion depois do buff dele? · testar onde o Max Potion é necessário"],
 ["precisa data on troque para Gyarados", "Falta testar a troca pro Gyarados"],
 ["No Encore jirachi. Encore pika. Drain punch is a roll para nocauteia", "Jirachi sem Encore · Pikachu dá Encore · o Drain Punch nocautear é roll"],
 ["se Earth Power gets u low Encore sacrifica", "Se o Earth Power te deixar com HP baixo · Encore e sacrifica"],
 ["se HJK misses once · sacrifica jirachi · Gallade 02", "Se o High Jump Kick errar uma vez · sacrifica o Jirachi · Gallade [0/2]"],
 ["pressione still se troque para moth", "Continue pressionando · se ele trocar pro Volcarona (moth)"],
 ["Shadow Ball once", "Um Shadow Ball"],
]
CMAP = { norm(o): n for o,n in C }
files=[f for f in glob.glob('data/teams/**/*.json',recursive=True) if '/emoji/' not in f]
hit={k:0 for k in CMAP}
for f in files:
    d=json.load(open(f,encoding='utf-8')); ch=False
    for n in d['nodes'].values():
        for s in n.get('steps',[]):
            t=s.get('text')
            if not t: continue
            k=norm(t)
            if k in CMAP and t!=CMAP[k]: s['text']=CMAP[k]; hit[k]+=1; ch=True
    if ch: json.dump(d,open(f,'w',encoding='utf-8'),ensure_ascii=False,indent=1)
print(f"aplicadas: {sum(hit.values())} ocorrências de {len(C)} regras")
nf=[o for o,k in zip([c[0] for c in C],CMAP) if hit[k]==0]
if nf:
    print("NÃO ENCONTRADOS:", len(nf))
    for x in nf: print("  -",x[:70])
